describe('Calculations check', () => {
  it('Do summation and subtraction', () => {
    cy.visit('/')

    cy.get('button').contains('1').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('-').click()
    cy.get('button').contains('8').click()
    cy.get('button').contains('=').click()
    cy.get('[data-test-display]').should('have.text', '5')
    cy.get('button').contains('CE').click()
  })

  it('Do multiplication and division', () => {
    cy.get('button').contains('2').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('4').click()
    cy.get('button').contains('=').click()
    cy.get('[data-test-display]').should('have.text', '5')
    cy.get('button').contains('CE').click()
  })

  it('Do calculations with parentheses', () => {
    cy.get('button').contains('2').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('(').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains(')').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('=').click()
    cy.get('[data-test-display]').should('have.text', '5')
    cy.get('button').contains('CE').click()
  })

  it('Do calculations with not integers', () => {
    cy.get('button').contains('0').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('4').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('=').click()
    cy.get('[data-test-display]').should('have.text', '3.333')
    cy.get('button').contains('CE').click()
  })
})