describe('Keypad and Display check', () => {
  it('Check clear all button', () => {
    cy.visit('/')

    cy.get('button').contains('1').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains('CE').click()
    cy.get('[data-test-display]').should('have.text', '')
  })
  
  it('Check clear button', () => {
    cy.get('button').contains('1').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('3').click()
    cy.get('[data-test-display]').should('have.text', '123')
    cy.get('button').contains('C').click()
    cy.get('[data-test-display]').should('have.text', '12')
    cy.get('button').contains('C').click()
    cy.get('[data-test-display]').should('have.text', '1')
    cy.get('button').contains('CE').click()
  })

  it('Check buttons display', () => {
    cy.get('button').contains('(').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains(')').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('5').click()
    cy.get('[data-test-display]').should('have.text', '(1+3)/2*0.5')
    cy.get('button').contains('CE').click()
  })

  it('Check equal button', () => {
    cy.get('button').contains('(').click()
    cy.get('button').contains('1').click()
    cy.get('button').contains('+').click()
    cy.get('button').contains('3').click()
    cy.get('button').contains(')').click()
    cy.get('button').contains('/').click()
    cy.get('button').contains('2').click()
    cy.get('button').contains('*').click()
    cy.get('button').contains('0').click()
    cy.get('button').contains('.').click()
    cy.get('button').contains('5').click()
    cy.get('button').contains('=').click()
    cy.get('[data-test-display]').should('have.text', '1')
    cy.get('button').contains('CE').click()
  })
})